---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-selfsigned-ca
  namespace: vault
spec:
  isCA: true
  commonName: Vault CA
  secretName: vault-ca-secret
  duration: 87660h0m0s
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-ca-issuer
  namespace: vault
spec:
  ca:
    secretName: vault-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-certificate
  namespace: vault
spec:
  secretName: vault-tls
  duration: 24h0m0s
  renewBefore: 2h24m0s  # roughly 10% of 24h
  dnsNames:
  - *.vault.svc.cluster.local
  - *.vault-internal
  - *.vault-internal.vault.svc.cluster.local
  - *.vault
  issuerRef:
    name: vault-ca-issuer
  commonName: vault cert
