---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-selfsigned-ca
  namespace: glueops-core-vault
spec:
  isCA: true
  commonName: Vault CA
  secretName: vault-ca-secret
  duration: 87660h0m0s # 10 years
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: vault-ca-issuer
  namespace: glueops-core-vault
spec:
  ca:
    secretName: vault-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-certificate
  namespace: glueops-core-vault
spec:
  secretName: vault-tls
  duration: 24h0m0s
  renewBefore: 2h24m0s  # roughly 10% of 24h
  dnsNames:
  - '*.glueops-core-vault.svc.cluster.local'
  - '*.vault-internal'
  - '*.vault-internal.glueops-core-vault.svc.cluster.local'
  - '*.glueops-core-vault'
  ipAddresses:
  - '127.0.0.1'
  issuerRef:
    name: vault-ca-issuer
  commonName: vault cert
