---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: injector-selfsigned-ca
  namespace: vault-test-2
spec:
  isCA: true
  commonName: Agent Inject CA
  secretName: injector-ca-secret
  duration: 87660h0m0s # 10 years
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: injector-ca-issuer
  namespace: vault-test-2
spec:
  ca:
    secretName: injector-ca-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: injector-certificate
  namespace: vault-test-2
spec:
  secretName: injector-tls
  duration: 24h
  renewBefore: 144m  # roughly 10% of 24h
  dnsNames:
  - vault-agent-injector-svc
  - vault-agent-injector-svc.vault-test-2
  - vault-agent-injector-svc.vault-test-2.svc
  issuerRef:
    name: injector-ca-issuer
  commonName: Agent Inject Cert
